spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/aiglass_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai}

server:
  error:
    include-stacktrace: always

springdoc:
  swagger-ui:
    enabled: true

app:
  ratelimit:
    requests-per-minute: 1000
  security:
    otp:
      includeInResponse: true

aliyun:
  sms:
    enabled: false

logging:
  level:
    root: INFO
    com.almousleck: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

